[package]
name = "tokentool"
version = "2.2.0"
description = "VTT Token Creation Utility"
authors = ["RPTools"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lopdf = { version = "0.33.0", default-features = false, features = ["nom_parser"] }
base64 = "0.22.1"
image = "0.25.1"
